name: Run RSpec tests Jococo
on:
  pull_request:
  workflow_dispatch:
jobs:
  run-rspec-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          # Not needed with a .ruby-version file
          ruby-version: 2.7
          # runs 'bundle install' and caches installed gems automatically
          bundler-cache: true
      - name: Run tests
        run: |
          bundle exec rspec
      - name: Generate JaCoCo Badge
        id: jacoco
        uses: cicirello/jacoco-badge-generator@v2

       - name: Log coverage percentage to the workflow log
         run: |
           echo "coverage = ${{ steps.jacoco.outputs.coverage }}"
           echo "branch coverage = ${{ steps.jacoco.outputs.branches }}"

       - name: Commit and push the badge (if it changed)
         uses: EndBug/add-and-commit@v7
         with:
           default_author: github_actions
           message: 'commit badge'
           add: '*.svg'
